const quizAllgemein = {
  title: "Allgemeinwissen Quiz",
  questions: [
{q: "Wie viele Bundesländer hat Deutschland?", a: ["14","16","18","12"], correct: 1},
{q: "Wer malte die Mona Lisa?", a: ["Picasso","Da Vinci","Van Gogh","Michelangelo"], correct: 1},
{q: "Wie heißt die Hauptstadt von Australien?", a: ["Sydney","Melbourne","Canberra","Perth"], correct: 2},
{q: "Welche Farbe hat Chlorophyll?", a: ["Rot","Grün","Blau","Gelb"], correct: 1},
{q: "Wie viele Kontinente gibt es?", a: ["5","6","7","8"], correct: 2},
{q: "Welcher Planet ist der Sonne am nächsten?", a: ["Venus","Merkur","Mars","Erde"], correct: 1},
{q: "Wie viele Zähne hat ein Erwachsener normalerweise?", a: ["28","30","32","34"], correct: 2},
{q: "Was ist die Hauptstadt von Kanada?", a: ["Toronto","Vancouver","Ottawa","Montreal"], correct: 2},
{q: "Wie heißt der höchste Berg der Welt?", a: ["K2","Mount Everest","Kilimandscharo","Mont Blanc"], correct: 1},
{q: "Welches Element hat das chemische Symbol 'O'?", a: ["Gold","Osmium","Ozon","Sauerstoff"], correct: 3},
{q: "Wie viele Planeten hat unser Sonnensystem?", a: ["7","8","9","10"], correct: 1},
{q: "Wer schrieb 'Faust'?", a: ["Schiller","Goethe","Lessing","Kafka"], correct: 1},
{q: "Wie viele Spieler hat eine Fußballmannschaft auf dem Feld?", a: ["9","10","11","12"], correct: 2},
{q: "Welcher Fluss fließt durch Paris?", a: ["Themse","Donau","Seine","Rhein"], correct: 2},
{q: "Wie heißt die Hauptstadt von Spanien?", a: ["Barcelona","Madrid","Sevilla","Valencia"], correct: 1},
{q: "Welches Tier ist das größte an Land lebende?", a: ["Elefant","Nilpferd","Giraffe","Nashorn"], correct: 0},
{q: "Wie viele Tage hat ein Schaltjahr?", a: ["364","365","366","367"], correct: 2},
{q: "Was ist H2O?", a: ["Sauerstoff","Wasser","Wasserstoff","Kohlenstoffdioxid"], correct: 1},
{q: "Welcher Planet wird als 'Roter Planet' bezeichnet?", a: ["Mars","Venus","Jupiter","Saturn"], correct: 0},
{q: "Wie heißt der längste Fluss der Welt?", a: ["Nil","Amazonas","Yangtse","Mississippi"], correct: 1},
{q: "Was ist die Hauptstadt von Italien?", a: ["Mailand","Rom","Neapel","Florenz"], correct: 1},
{q: "Wie viele Ringe hat die olympische Flagge?", a: ["4","5","6","7"], correct: 1},
{q: "Welches Land hat die größte Bevölkerung?", a: ["USA","Indien","China","Indonesien"], correct: 2},
{q: "Wie viele Minuten hat eine Stunde?", a: ["60","100","90","30"], correct: 0},
{q: "Wer erfand das Telefon?", a: ["Edison","Tesla","Bell","Newton"], correct: 2},
{q: "Wie viele Seiten hat ein Würfel?", a: ["4","6","8","10"], correct: 1},
{q: "Was ist die Hauptstadt von Japan?", a: ["Kyoto","Osaka","Tokio","Hiroshima"], correct: 2},
{q: "Welcher Kontinent ist der größte?", a: ["Afrika","Asien","Europa","Amerika"], correct: 1},
{q: "Wie viele Beine hat eine Spinne?", a: ["6","8","10","12"], correct: 1},
{q: "Was ist das chemische Symbol für Gold?", a: ["Gd","Au","Ag","Go"], correct: 1},
{q: "Wie viele Wochen hat ein Jahr?", a: ["48","50","52","54"], correct: 2},
{q: "Wer war der erste Mensch auf dem Mond?", a: ["Buzz Aldrin","Neil Armstrong","Yuri Gagarin","Michael Collins"], correct: 1},
{q: "Wie viele Sterne hat die Flagge der EU?", a: ["10","12","15","20"], correct: 1},
{q: "Was ist die Hauptstadt von Norwegen?", a: ["Oslo","Stockholm","Kopenhagen","Helsinki"], correct: 0},
{q: "Wie viele Sinne hat der Mensch klassisch?", a: ["4","5","6","7"], correct: 1},
{q: "Welcher Ozean ist der größte?", a: ["Atlantik","Indischer Ozean","Pazifik","Arktischer Ozean"], correct: 2},
{q: "Wie viele Chromosomen hat der Mensch?", a: ["42","44","46","48"], correct: 2},
{q: "Was ist die Hauptstadt von Brasilien?", a: ["Rio de Janeiro","São Paulo","Brasília","Salvador"], correct: 2},
{q: "Wie viele Nullen hat eine Milliarde?", a: ["6","9","12","15"], correct: 1},
{q: "Welcher Planet hat Ringe?", a: ["Mars","Venus","Saturn","Merkur"], correct: 2},
{q: "Wie heißt das größte Säugetier der Welt?", a: ["Elefant","Blauwal","Nashorn","Giraffe"], correct: 1},
{q: "Was ist die Hauptstadt der Schweiz?", a: ["Zürich","Genf","Bern","Basel"], correct: 2},
{q: "Wie viele Bundeskanzler hatte Deutschland seit 1949 (bis 2021)?", a: ["6","8","9","10"], correct: 2},
{q: "Wie viele Planeten sind mit bloßem Auge sichtbar?", a: ["3","5","7","9"], correct: 1},
{q: "Was ist die Hauptstadt von Ägypten?", a: ["Kairo","Alexandria","Luxor","Gizeh"], correct: 0},
{q: "Wie viele Liter hat ein Kubikmeter?", a: ["10","100","1000","10000"], correct: 2},
{q: "Welcher Kontinent hat die meisten Länder?", a: ["Asien","Afrika","Europa","Südamerika"], correct: 1},
{q: "Wie viele Herzen hat ein Oktopus?", a: ["1","2","3","4"], correct: 2},
  ]
};
